
/*1.Distinct Cities: List all unique cities where Swiggy is currently operating based on this dataset.

2.High-Value Dishes: Find all dishes that have a price (Price_INR) greater than 500.

3.City-wise Revenue: Calculate the total revenue (Price_INR) generated by each city and sort it from highest to lowest.

4.Top Rated Categories: Find the average rating for each food Category (e.g., North Indian, Chinese) and display only those with an average rating above 4.2.

5.Order Volume by Location: Identify the top 5 locations with the highest number of orders.

6.Price Segment Analysis: Group dishes into 'Budget' (<200), 'Mid-range' (200-500), and 'Premium' (>500). Count dishes in each.

7.Customer Preferences: Find the most expensive dish in each city along with its price.

8.Low Volume / High Quality: Identify restaurants that have a Rating above 4.5 but a Rating_Count of less than 50 (Potential "Hidden Gems").

9.Monthly Order Trend: Count the total number of orders placed in each month using the Order_Date column.

10.Revenue Contribution %: Calculate the percentage contribution of each city to the total overall revenue.

11.Repeat Customer Potential: Find restaurants where the rating_count is high but the rating is low (e.g., < 3.0).

12Peak Activity Days: Use TO_CHAR to find which day of the week (Monday, Sunday, etc.) has the highest total orders.

                             lets solve the questions*/

--1.Distinct Cities: List all unique cities where Swiggy is currently operating based on this dataset.
select 
distinct(city) as unique_cities
from swiggy;

--2.High-Value Dishes: Find all dishes that have a price (Price_INR) greater than 500.

select 
dish_name,
price_inr 
from swiggy 
where price_inr>500;

--3.City-wise Revenue: Calculate the total revenue (Price_INR) generated by each city and sort it from highest to lowest.

select
city,
round(sum(price_inr)::numeric,2) as total_revenue
from swiggy
group by 1
order by 2 desc;

--4.Top Rated Categories: Find the average rating for each food Category (e.g., North Indian, Chinese) and display only those with an average rating above 4.2.

select
category,
round(avg(rating)::numeric,2) as avg_rating
from swiggy
group by 1
having avg(rating)>4.2
order by 2 desc;

--5.Order Volume by Location: Identify the top 5 locations with the highest number of orders.
select
location,
count(*) 
from swiggy 
group by 1
order by 2 desc
limit 5;

--6.Customer Preferences: Find the most expensive dish in each city along with its price.
with dish_rank as 
	(select city,
	dish_name,
	max(price_inr) as max_price,
	dense_rank() over(partition by city order by max(price_inr) desc ) as rank
	from swiggy
	group by 1,2)
select 
	city,
	dish_name,
	max_price,
	rank
from dish_rank 
where rank=1;

--7 Low Volume / High Quality: Identify restaurants that have a Rating above 4.5 but a Rating_Count of less than 50
select
	restaurant_name,
	round(avg(rating)::numeric,2) as rating,
	sum(rating_count) as rating_count 
from swiggy
group by 1
 having avg(rating)>4.5 and sum(rating_count)<50
 order by 3;

--8.Monthly Order Trend: Count the total number of orders placed in each month using the Order_Date column.
select 
TO_CHAR(order_date, 'FMMonth-YYYY') AS monthy_order,
count(*) 
from swiggy
group by 1,
extract(month from order_date),
extract (year from order_date)
order by 
extract(month from order_date) asc,
extract (year from order_date) asc;

--9Revenue Contribution %: Calculate the percentage contribution of each city to the total overall revenue.
select 
city,
round(sum(price_inr)::numeric,2) as total_revenue,
round(((sum(price_inr)*100)/sum(sum(price_inr))over())::numeric,2) as pecentage
from swiggy 
group by 1
order by 3 desc;
select sum(price_inr) from swiggy

--10Price Segment Analysis: Group dishes into 'Budget' (<200), 'Mid-range' (200-500), and 'Premium' (>500). Count dishes in each.

select 
case 
	when price_inr<200 then 'low'
	when price_inr between 200 and 500 then 'mid_range'
	else 'premium'
end as budget_category,
count(dish_name),
round(avg(rating)::numeric,2) as avg_rating
from swiggy
group by 1
order by 2 desc;

--11Repeat Customer Potential: Find restaurants where the rating_count is high but the rating is low (e.g., < 3.0).

select
restaurant_name,
sum(rating_count) as rating_count,
round(avg(rating)::numeric,2) as avg_rating
from swiggy 
where rating<3.0
group by 1
order by 2 desc

--12Peak Activity Days: Use TO_CHAR to find which day of the week (Monday, Sunday, etc.) has the highest total orders.

SELECT 
    TO_CHAR(order_date, 'FMDAY') AS day_of_week, 
    COUNT(*) AS total_orders,
    ROUND((COUNT(*) * 100.0 / SUM(COUNT(*)) OVER()), 2) AS order_percentage
FROM swiggy
GROUP BY 1, EXTRACT(DOW FROM order_date)
ORDER BY total_orders DESC;












